# Dockerfile for React Client (Vite + React + TypeScript)
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ARG VITE_API_URL
ENV VITE_API_URL=${VITE_API_URL}

RUN if [ -z "${VITE_API_URL}" ]; then echo "Error: VITE_API_URL is not set. Please set it as a build argument."; exit 1; fi

RUN npm run build

# Serve using Nginx
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
