version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - "5253:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - api
    environment:
      - DOCKER_ENV=http://api:8080
