// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250608181020_AddIndexesToUser")]
    partial class AddIndexesToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Birthdate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comments")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("First_name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ip_address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Last_name")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Registration_dttm")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Salary")
                        .HasColumnType("REAL");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Birthdate")
                        .HasDatabaseName("IX_User_Birthdate");

                    b.HasIndex("Comments")
                        .HasDatabaseName("IX_User_Comments");

                    b.HasIndex("Country")
                        .HasDatabaseName("IX_User_Country");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_User_Email");

                    b.HasIndex("First_name")
                        .HasDatabaseName("IX_User_First_name");

                    b.HasIndex("Gender")
                        .HasDatabaseName("IX_User_Gender");

                    b.HasIndex("Last_name")
                        .HasDatabaseName("IX_User_Last_name");

                    b.HasIndex("Registration_dttm")
                        .HasDatabaseName("IX_User_Registration_dttm");

                    b.HasIndex("Salary")
                        .HasDatabaseName("IX_User_Salary");

                    b.HasIndex("Title")
                        .HasDatabaseName("IX_User_Title");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
